### PR TITLE
Drop duplicate hint

### PR DESCRIPTION
**Pull request by fantix**
Depends on https://github.com/edgedb/edgedb-rust/pull/220

### CODE REVIEW

**Comment by tailhook** [comment]
This should not be needed with the new connection builder code, right?

**Comment by tailhook** [comment]
@fantix :arrow_up: ?

**Comment by fantix** [comment]
Ah I think there's some code logic to optimize in edgedb/edgedb-rust#220 - I'll create 2 updates.

**Comment by fantix** [comment]
Oh sorry I mean this PR should be merged

**Comment by fantix** [comment]
This PR is dropping the hint, because it's moved to the edgedb-rust client in `NoCloudConfigFound`.

**Review by tailhook — APPROVED** [review]

**Comment by tailhook** [comment]
Oops! Sorry I've misread the PR, and thought it adds things.

**Pull request merged**
