### PR TITLE
Init project in self install

### PR DESCRIPTION
**Pull request by tailhook**
This effectively does `project init` in `curl .. | sh` pipeline.

Note: we don't do project init when using `-y` flag. This latter is for scripting and it's better to use explicit `project init` in scripts.

### CODE REVIEW

**Comment by 1st1** [comment]
I don't like running init by default.  If this is to simplify our tutorials, maybe we should add an explicit `-- --init` flag specifically to the install command we feature in our tutorials. But the default one should not init; I don't think that by default users will run this command in their specific project dir.

**Comment by elprans** [comment]
> add an explicit `-- --init` flag

The installer is interactive by default, why can't we simply ask?  E.g "Detected an EdgeDB project directory, would you like to initialize a database instance for it?"

**Comment by 1st1** [comment]
> E.g "Detected an EdgeDB project directory, would you like to initialize a database instance for it?"

Is that what this PR is doing? I can't see that from the diff.

**Comment by elprans** [comment]
> Is that what this PR is doing?

It's detecting the project dir, but doesn't ask currently.

**Pull request merged**
