### PR TITLE
run tests on pull request

### PR DESCRIPTION
**Pull request by CodesInChaos**
It'd be useful to run the CI on pull requests to prevent merging broken code.

### CODE REVIEW

**Comment by CodesInChaos** [comment]
Not sure if it's necessary to test the full OS matrix on pull requests

**Comment by tailhook** [comment]
Tests do currently run on PRs. Where do you see the problem?

**Comment by CodesInChaos** [comment]
I think they only run on pushes, not pull requests so they only run after you merged the pull request but not while it's open.

**Comment by tailhook** [comment]
I see tests on your PR too, don't you have that:
image

**Comment by CodesInChaos** [comment]
I think it uses the workflow config defined in the pull request.

Take a look at my pull requests to edgedb-rust:
* https://github.com/edgedb/edgedb-rust/pull/34 ran tests because it added the trigger to the workflow
* https://github.com/edgedb/edgedb-rust/pull/35 and https://github.com/edgedb/edgedb-rust/pull/33 didn't

(btw I don't see any CLA checks on edgedb-cli, is that set up correctly?)

**Comment by tailhook** [comment]
Ah, right. I see now. Thanks!

**Comment by tailhook** [comment]
> (btw I don't see any CLA checks on edgedb-cli, is that set up correctly?)

Probably not. Thanks for noticing it.

**Comment by CodesInChaos** [comment]
Looks like this has the side effect that if the feature branch is in the main repo, the tests run twice (once triggered by `push`, once by `pull_request`. Perhaps it'd make sense to limit the push trigger to the `master` branch.

**Pull request merged**
