### PR TITLE
Status command update

### PR DESCRIPTION
**Pull request by tailhook**

### CODE REVIEW

**Comment by elprans** [comment]
I'm a bit confused about the distinction between `--verbose` and `--extended`.  Do we really need two, is there a way to combine them somehow?

**Comment by tailhook** [comment]
Here is the basic difference:
```
ubuntu@ip-172-26-7-203:~$ ./edgedb server status --extended
default:
  Status: running, pid 21705
  Pid: 21705
  Service file: exists
  Version: 1-alpha4 (nightly)
  Installation method: Native System Package
  Startup: auto
  Port: 5656
  Port status: occupied
  Data directory: /home/ubuntu/.local/share/edgedb/data/default
  Data status: upgrading 1.0a4.dev78+g3c05fe5-2020071700~xenial.nightly -> 1.0a4.dev78+g3c05fe5-2020071700~xenial.nightly for 2h 6m 58s
  Backup: present, done 2h 6m 58s ago
ubuntu@ip-172-26-7-203:~$ ./edgedb server status -v
● edgedb-server@default.service - EdgeDB Database Service, instance "default"
   Loaded: loaded (/home/ubuntu/.config/systemd/user/edgedb-server@default.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-07-17 15:29:56 UTC; 2h 6min ago
     Docs: https://edgedb.com/
 Main PID: 21705 (/usr/lib/x86_64)
   CGroup: /user.slice/user-1000.slice/user@1000.service/edgedb\x2dserver.slice/edgedb-server@default.service
           ├─21705 /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/bin/python3.8 /usr/bin/edgedb-server-1-alpha4 --data-dir=/home/ubuntu/.loc
           ├─21712 /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/bin/postgres -D /home/ubuntu/.local/share/edgedb/data/default --port=54942
           ├─21714 postgres: checkpointer                                                                                                     
           ├─21715 postgres: background writer                                                                                                
           ├─21716 postgres: walwriter                                                                                                        
           ├─21717 postgres: autovacuum launcher                                                                                              
           ├─21718 postgres: stats collector                                                                                                  
           ├─21719 postgres: logical replication launcher                                                                                     
           ├─21730 /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/bin/python3.8 -m edb.server.procpool.worker --cls-name edb.server.compiler
           ├─21731 /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/bin/python3.8 -m edb.server.procpool.worker --cls-name edb.server.compiler
           ├─22298 /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/bin/python3.8 -m edb.server.procpool.worker --cls-name edb.server.compiler
           └─22305 /usr/lib/x86_64-linux-gnu/edgedb-server-1-alpha4/bin/python3.8 -m edb.server.procpool.worker --cls-name edb.server.compiler

Jul 17 15:29:51 ip-172-26-7-203 systemd[18474]: Starting EdgeDB Database Service, instance "default"...
Jul 17 15:29:52 ip-172-26-7-203 edgedb-server-1-alpha4[21705]: INFO 21705 2020-07-17 15:29:52,327 edb.server: EdgeDB server (1.0-alpha.4+dev.7
Jul 17 15:29:53 ip-172-26-7-203 systemd[18474]: edgedb-server@default.service: Got notification message from PID 21712, but reception only per
Jul 17 15:29:56 ip-172-26-7-203 edgedb-server-1-alpha4[21705]: INFO 21705 2020-07-17 15:29:56,988 edb.server: Serving on 127.0.0.1:5656
Jul 17 15:29:56 ip-172-26-7-203 edgedb-server-1-alpha4[21705]: INFO 21705 2020-07-17 15:29:56,989 edb.server: Serving on /run/user/1000/edgedb
Jul 17 15:29:56 ip-172-26-7-203 edgedb-server-1-alpha4[21705]: INFO 21705 2020-07-17 15:29:56,990 edb.server: Serving admin on /run/user/1000/
Jul 17 15:29:56 ip-172-26-7-203 systemd[18474]: Started EdgeDB Database Service, instance "default".
```
Generally I like what systemd shows and I think this is quite useful. But I don't want to replicate that for macos, at least for now.

But `--extended` shows a bunch of debug info, important to find out what have gone wrong when last upgrade (or other command) was interrupted or why start doesn't work. But it doesn't fit on the same screen with systemd output. Also `--all --extended` works nice, but `-v -all` with a long list of systemd screens wouldn't look nice.

**Comment by tailhook** [comment]
That said we can rename `--extended` to `--debug-info` or something.

**Comment by elprans** [comment]
Maybe introduce verbosity levels? Like `--verbose=2` or `-vv`.

**Comment by elprans** [comment]
`-vv` could show both the extended info and systemd status

**Comment by tailhook** [comment]
> `-vv` could show both the extended info and systemd status

There already three styles of things in systemd data (fields, tree and log). And aligning our output to that would be hard. So bunch of messy things doesn't sound good. And if `--all -vv` shows both, it's horrible. While `--all --extended` is very important to report a bug or ask for help.

**Comment by elprans** [comment]
OK, if keeping them separate, then we need more descriptive names for the output modes.

**Comment by elprans** [comment]
Perhaps `edgedb server status --service` instead of `--verbose`?

**Comment by tailhook** [comment]
Well, better names could work. I'm not sure `--service` does it for me. We can probably just do `--systemd`? As we don't have anything on macos yet.

**Comment by elprans** [comment]
> We can probably just do --systemd? As we don't have anything on macos yet.

I'd prefer we didn't have system-specific flags if possible.  And why nothing on macOS?  `launchctl print` is a thing (less informative than `systemctl status`, but still

**Comment by tailhook** [comment]
Okay updated to `--service`. (Since the output is already system-dependent it doesn't help much that the cli argument is the same, so I don't care that much both ways)

**Pull request merged**
