### PR TITLE
Update github's set-env conventions

### PR DESCRIPTION
**Pull request by tailhook**

### CODE REVIEW

**Review by elprans — APPROVED** [review]
Oh. We need to do this across all our workflows. \cc  @ambv

**Comment by tailhook** [comment]
@elprans update https://github.com/elprans/gha-setup-vcpp-build-tools (by merging upstream) to get windows building

**Comment by elprans** [comment]
@tailhook There's only dependency bumps upstream, was that the problem? (I merged `ms-build/master`)

**Comment by tailhook** [comment]
> @tailhook There's only dependency bumps upstream, was that the problem? (I merged `ms-build/master`)

Perhaps yes, I'm not sure. I've seen that there is a closed issue about that.

**Pull request merged**
