### PR TITLE
Make `migration create` use the question crate

### LINKED ISSUE #429: Interactive prompts are not consistent
`edgedb project init` uses `>` as a user input prompt while `edgedb migration create` doesn't print any prompt at all. Perhaps the `>` prompt should be used every time user input is solicited interactively. Or at least the prompt should be consistent. 

- EdgeDB CLI Version: EdgeDB CLI 1.0.0-beta.2+d20210803.g62dbcf9e8
- OS Version: Linux 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. `edgedb project init`
2. `edgedb migration create`

### PR DESCRIPTION
**Pull request by 1st1**
Fixes #429

### CODE REVIEW

**Comment by 1st1** [comment]
The consequence of this change is that by default we only show the short prompt now; a user needs to type `?` to show the help, which I think is a good thing (less noise).

Screenshot from 2021-08-10 12-46-24

**Comment by 1st1** [comment]
I've also added colors & updated rendering of `h`

Screenshot from 2021-08-10 13-58-37

**Review by elprans — APPROVED** [review]
LGTM

**Comment by 1st1** [comment]
Fixed "confirm" to "confirmed" with my recent force push

**Review by fantix — APPROVED** [review]
Nice!

**Comment by 1st1** [comment]
@tailhook please take a look tomorrow at this. The changes are fairly trivial, but the UX improvements are nice and I decided to merge it now to be part of the release build.

**Comment by tailhook** [comment]
Using blocking in async can cause troubles in future, but currently there is nothing that depends on that, so it's fine. Other than that it's good.

**Pull request merged**
