### PR TITLE
Print current branch/database in REPL

### PR DESCRIPTION
**Pull request by quinchs**
Fixes https://github.com/edgedb/edgedb-cli/issues/1250

### CODE REVIEW

**Review by aljazerzen — APPROVED** [review]
This basically doubles the time between user hitting enter and CLI being ready for next command.

But there is no other way, so I guess ok.

**Comment by msullivan** [comment]
> This basically doubles the time between user hitting enter and CLI being ready for next command.
> 
> But there is no other way, so I guess ok.

Can't we fetch it only once at connection time?

**Comment by aljazerzen** [comment]
Oh, yes - branch cannot be changed with EdgeQL queries, so it can be cached for the whole duration of a connection.

That said: we could just the the "branch" connection parameter and to make any requests to the database. I guess this would be more fragile since we both "database" param and "branch" param and some non-trivial logic deciding which branch we actually open the connection to.

Bottom line: current approach is good

**Comment by aljazerzen** [comment]
The interactive tests are failing because they expect to have "edgedb>" command prompt, but get "main>" instead.

**Comment by quinchs** [comment]
> The interactive tests are failing because they expect to have "edgedb>" command prompt, but get "main>" instead.

I'll fix that

**Pull request merged**
