### PR TITLE
List cloud instances by default

### PR DESCRIPTION
**Pull request by fantix**
Drop `--cloud` option in `edgedb instance list`, and list cloud instances in the same table if logged in.

### CODE REVIEW

**Comment by tailhook** [comment]
I think we should probably enforce some timeout on cloud instance list in addition to "intermediate feedback". Some 30-60 sec probably. On regular remote instances we have a timeout for each attempt I think.

**Comment by tailhook** [comment]
> Drop `--cloud` option in `edgedb instance list`, and list cloud instances in the same table if logged in.

I also thing that some `--cloud[-only]` filter might make sense for scripting. But can be a follow up PR.

**Review by tailhook — COMMENTED** [review]
Generally looks good, two things to be done:
1. Add a timeout
2. Figure out statuses

**Review by elprans — APPROVED** [review]

**Comment by tailhook** [comment]
@fantix, one thing is missing here: if cloud is timeouted or otherwise inaccessible, we should print local (and probably remote) instances, then print error and exit with erroneous exit code. This is a common case for offline work, so list of local instances should be there to work without too much hassle.

**Comment by fantix** [comment]
Right, let me create another PR.

**Pull request merged**
