### PR TITLE
migrate: Auto-set `allow_bare_ddl` on first migration

### PR DESCRIPTION
**Pull request by tailhook**

### CODE REVIEW

**Comment by tailhook** [comment]
Needs edgedb/edgedb#3363 merged (and a nightly release) to make tests working.

**Comment by 1st1** [comment]
@fantix please take a look

**Review by fantix — APPROVED** [review]
Tested, all works fine.

> https://edgedb.com/p/bare_dll

We'll create this page, right?

**Comment by tailhook** [comment]
> Tested, all works fine.
> 
> > https://edgedb.com/p/bare_dll
> 
> We'll create this page, right?

Yes @colinhacks should take care of that.

**Comment by coreyward** [comment]
Heads up, the CLI links to https://edgedb.com/p/bare_ddl after the first `edgedb migrate` command is run, which redirects to this thread. Since “DDL” is not defined in the [Quickstart](https://www.edgedb.com/docs/guides/quickstart) or here, this is liable to be confusing to new users (👋 ).

> Note: adding first migration disables DDL. More info: https://edgedb.com/p/bare_ddl

**Comment by 1st1** [comment]
> Heads up, the CLI links to https://edgedb.com/p/bare_ddl after the first edgedb migrate command is run, which redirects to this thread. Since “DDL” is not defined in the [Quickstart](https://www.edgedb.com/docs/guides/quickstart) or here, this is liable to be confusing to new users (👋 ).

@colinhacks

**Comment by colinhacks** [comment]
Trying to explain DDL in the quickstart is also liable to be confusing to new users. I'm in favor of dropping this warning entirely. I think it should only be surfaced when users attempt to run DDL commands.

**Comment by 1st1** [comment]
> I'm in favor of dropping this warning entirely. I think it should only be surfaced when users attempt to run DDL commands.

+1

**Comment by 1st1** [comment]
@fantix @tailhook can you drop it?

**Pull request merged**
