### PR TITLE
Do not block Docker installation method on missing/inaccessible socket

### PR DESCRIPTION
**Pull request by elprans**
There is no Docker deamon Unix socket on Windows (there's a TCP port and
a named pipe, though [1]).  But, more importantly, the CLI itself
doesn't use the socket in any way, so the check doesn't seem to be
useful.

[1] https://docs.docker.com/desktop/faqs/#how-do-i-connect-to-the-remote-docker-engine-api

### CODE REVIEW

**Comment by tailhook** [comment]
We don't use socket, but mere presense of docker CLI doesn't mean docker daemon is running, so shouldn't assume docker works on the system. Note: if we detect docker as supported, but it doesn't actually work, using `--method=package` becomes nightmare too (i.e. `list-versions` checks both, `init` may hit both, `uninstall` checks both, and so on).

On windows we may suppress the check for now.

**Comment by elprans** [comment]
> We don't use socket, but mere presense of docker CLI doesn't mean docker daemon is running, so shouldn't assume docker works on the system.

I still think checking the socket is not the best strategy to test if docker is working.  Why not run some CLI command as a test instead?

**Comment by tailhook** [comment]
> > We don't use socket, but mere presense of docker CLI doesn't mean docker daemon is running, so shouldn't assume docker works on the system.
> 
> I still think checking the socket is not the best strategy to test if docker is working. Why not run some CLI command as a test instead?

Because it's slow, and a bunch of unexpected error codes and messages, which is unclear how to deal with. Checking for socket while is not perfect worked well so far.

And I think we may use docker API eventually anyway, so you don't need command-line and socket is the only thing we'll use.

**Comment by tailhook** [comment]
Superseded by #242

**Pull request closed without merging**
